### PR TITLE
Install script

### PR DESCRIPTION
**Pull request by NielsKorschinsky**
- New feature: Install Script
  - Automatically install SPPMon
  - Creates config file 
  - Creates Influx Users
  - Installs crontab configurations
 
 Missing:
 - [x] Implementation of feedback
  - [x] Grafana-Reader database permissions
  - [x] remove pullScript.sh (to be done before merging)
  - [x] Grafana Config file
  - [x] Code-Documentation
  - [ ] Wiki-Documentation
 
 Optional features: 
 - [x] `--autoConfirm` for an automatic install with a lot less prompts
 - [x] logging of executed steps/output
 
Be aware this also creates a password file. This file **needs** to be deleted afterwards (either by prompt of the script itself or manually if you choose not to delete/abort).

This Branch is getting squashed to avoid this massive commit-spam.

Edit:

- It is a must to edit the wiki once this branch is life to fix the `retention`-typo.

### CODE REVIEW

**Comment by NielsKorschinsky** [comment]
- [ ] Operating System check
- [ ] Free Space check
- [ ] Discussion weather to install exact versions or use existing ones
- [ ] Docker?
- Allowed user to determine where to place the influx-database. I don't see any option to move other grafana/python installs/data, since these do not really store anything.
- Improved wording in the welcome file
- Added additonal information to the prompt of `yum upgrade`
- fixed minor typo in the path when setting up python
-  Enabled echo for any [yes/no] confirmation
- Disabled echoing for passwords
- Replaced plain text confirmation on passwords with repeating input to confirm.
   - Python: Added new arg `is_password` for methods `readAuthOrInput` and `prompt_string`, using `getpass` instead of `input`.
   - Bash: Added function `promptPassword`, disallowing some symbols (may need to be extended to all json file inputes if it bugs)

**Comment by baslerj** [comment]
@NielsKorschinsky I have completed a bunch more testing and have pushed a commit containing a number of minor fixes that I'd like to have you review.  I have noted a few more feature requests:

- I second the idea for the --autoConfirm.  All of the enter y/n to confirm input becomes very tedious.  Also, there are way too many questions in the crontab setup portion.  One alternative for the crontab may be to ask upfront whether default timing options are acceptable and then only ask the detailed questions when the advanced path is taken.
- Prompt for a storage location for Grafana files just as you have added for InluxDB files.
- When the is a saved auth file from a previous session, the prompts to enter passwords a second time accept <enter> without any checking.

**Comment by baslerj** [comment]
Also, can you change this pull request to first merge in with the develop branch?

**Comment by baslerj** [comment]
I pushed in another bugfix for the issue where sppmon.py fails with the following error after running through the install script
```
  File "/home/sppmon/spectrum-protect-sppmon/python/influx/influx_client.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
The scripts which install Python is upgrading pip and installing the contents of requirements.txt without sudo.  This results in the modules being installed in a .local branch of my /home directory which is not picked up by sppmon.py when it is executed with sudo permissions.

**Comment by baslerj** [comment]
After running through the installation script, running sppmon.py --test fails on the Influx validation steps with the following error.
```
> Testing and configuring InfluxDB
Exception in FILE: influx_client.py, Line: 132, Exception: <class 'requests.exceptions.SSLError'>
Exception Message: HTTPSConnectionPool(host='9.11.64.58', port=8086): Max retries exceeded with url: /ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))
```
I took the install script path of having a self-signed certificate generated.  In the .config file, I believe the following line should be false:
`        "verify_ssl": true,
`

**Comment by baslerj** [comment]
Running sppmon.py with --test also discover an issue with the ssh connection to the SPP server.  The issue is the default port taken for the srv_port parameter is 443, which is only appropriate for the REST API connection.  This should default to port 22.

```
>> Testing now connection and commands of 2 registered ssh-clients.
Exception: Error reading SSH protocol banner
```

**Comment by NielsKorschinsky** [comment]
@baslerj Thanks a lot for all your feedback and instant fixes. I'm sorry that you found that much.
I like the screen clearing, it makes following the process way easier.
I've changed it to the dev branch.

1. I've implemented now a --alwaysConfirm argument. This speeds up the install process by a lot.
I still have a few confirms which I've labeled as `alwaysConfirm` since these are kinda important. After Feedback I might delete these too:
- Starting a new part of SPPMon install script
- Password Confirms
- Failed to create user influx restart confirmation (defaults to no, therefore the strict confirm)

2. I still have a error that sometimes the influx user creation fails. I will investigate there very soon.
Other errors:
- [ ] When setting up the config file it seems like the auth file is not working
- [ ] No message when passwords do not match in config file setup

3. [ ] I'm going to check for the grafana config file. currently we do not change the default location but it is good to do this.

4. Executing pip as sudo is not recommended and it warns to break permissions. I leave the sudo there, but have to check for alternatives or a double-install as sudo and without.

I will continue to implement and fix these issues later.

**Comment by NielsKorschinsky** [comment]
- Added access rights control for auth file and config files
- fixed typo `jobLog_retention` 
- added info when passwords did not match
- removed confirm on passwords if autoConfirm is used
-  some features from the request above

**Comment by NielsKorschinsky** [comment]
>     * When there is a saved auth file from a previous session, the prompts to enter passwords a second time accept  without any apparent check for matching to the first entered password.
@baslerj I'm not sure exactly where you found this bug. 
If just pressing enter it uses the default value within the confirm, which is the previous entered password.
If the first password is different to the default, just hitting enter will fail here, but it will never accept if the second password does not match the first one (beside enter case).

**Comment by NielsKorschinsky** [comment]
Also missing Documentation before merging

**Comment by NielsKorschinsky** [comment]
Merged dev into install script to stop this Bot spam of requiring a rebase.

**Comment by NielsKorschinsky** [comment]
The install-script is finished. 
I'm going to only edit the wiki from now on.
Please test the script and give me feedback if any changes are desired

**Comment by NielsKorschinsky** [comment]
merging (squash) on behalf of jason

**Pull request merged**
